### ISSUE TITLE
`--lang-list` or `--lang-list (asian language)` does not work

### ISSUE THREAD

**Issue by 1nterp** [behave/behave#1053]
### Version
1.2.6 (But I believe 1.2.7 would not work, too)

### Reproduction
```bash
behave --lang-list
## or
behave --lang-help ja ## Japanese
```

### Symptoms
```
Traceback (most recent call last):
  File "/INT3/homes/i520508/work/hc-flex-bdd/venv/bin/behave", line 8, in <module>
    sys.exit(main())
  File "/INT3/homes/i520508/work/hc-flex-bdd/venv/lib/python3.7/site-packages/behave/__main__.py", line 185, in main
    return run_behave(config)
  File "/INT3/homes/i520508/work/hc-flex-bdd/venv/lib/python3.7/site-packages/behave/__main__.py", line 97, in run_behave
    trans["native"][0]))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 28-30: ordinal not in range(256)
```

### Note
[convert_i18n_yaml.py](https://github.com/behave/behave/blob/main/.attic/convert_i18n_yaml.py) seems generating UTF-8 encoded contents. So.. is this just my personal issue? Could anyone take a look at it? Thanks.

**Comment by 1nterp** [comment]
Seems duplicated with #134, let me close quickly.
