### ISSUE TITLE
Crash when executing feature:line if feature file contains scenario without examples

### ISSUE THREAD

**Issue by callejerog** [behave/behave#1056]
executing "behave feature:line" brings to exception when feature file contains at least one scenario without examples:

```
Exception TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\Scripts\behave.exe\__main__.py", line 7, in <module>
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\__main__.py", line 183, in main
    return run_behave(config)
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\__main__.py", line 127, in run_behave
    failed = runner.run()
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\runner.py", line 804, in run
    return self.run_with_paths()
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\runner.py", line 818, in run_with_paths
    features = parse_features(feature_locations, language=self.config.lang)
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\runner_util.py", line 334, in parse_features
    current_feature = scenario_collector.build_feature()
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\runner_util.py", line 193, in build_feature
    self.all_scenarios = self.feature.walk_scenarios()
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 209, in walk_scenarios
    all_scenarios.extend(scenario_outline.scenarios)
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 1017, in scenarios
    self._scenarios = builder.build_scenarios(self)
  File "C:\Users\giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 889, in build_scenarios
    for row_index, row in enumerate(example.table):
TypeError: 'NoneType' object is not iterable 
```

Feature  file:

```gherkin
Feature: Showing off behave (tutorial01)

    Scenario Outline: Examples here
        Then just print <username> <email> <password>
        Examples: PROVA
            | username | email | password |
            | pippo | pippo@mail.com | paperino |

    Scenario: Run a simple test
        Given we have behave installed
        When we implement a test
        Then behave will test it for us!
```

**Comment by callejerog** [comment]
I investigated more. The scenario must be updated, sorry for previous message, was not enough.
I have implemented examples from file as per other threads suggestions here, so try using following file as feature file.
The command that led to exception:  behave feature_file:line where line is the last one.

'''
Feature: Showing off behave (tutorial01)

  @examples_from_file
  Scenario Outline: Examples from file
    Then just print <username> <email> <password>

    # Data folder: features\data\tutorial01_basics\Examples_from_file
    Examples: Examples_from_file

  Scenario Outline: Examples here 
    Then just print <username> <email> <password>
    Examples: PROVA
    | username | email | password |
    | pippo | pippo@mail.com | paperino |
'''

Note that environment.py is not relevant, before_all not called before exception happening.

**Comment by jenisys** [comment]
I assume that your implementation of „examples_from_file“ is faulty.
This should cause that the generation of the scenarios in the first ScenarioOutline probably fails with `example.table = None`.

HINT: 
The stack trace from above would normally be caused by `Examples: …` without a table (like in the first ScenarioOutline).

**Comment by callejerog** [comment]
Sorry but I think it's not.
The only place I use that tag is in before_feature:

```
from_file_scenarios = (scenario for scenario in feature.scenarios if 'examples_from_file' in scenario.tags)
```

If I execute behave on whole feature file it works.
If I execute file:row where row is the one with example written in the file itself(scenario unrelated with the tagged one) it crashes before passing in before_feature method (also before before_all).

How can my implementation be the reason?

**Comment by jenisys** [comment]
Which `behave` version are you using (because current HEAD has different line numbers) ?

* The last stable on `pypi.org`: v1.2.6
* The Github repository HEAD
* …

**HINT:**
Retry your problem with the current HEAD of the Github repository.
The current implementation checks if the `example.table` is `None` just before the `for-loop`.
Therefore, your error syndrome is already fixed.

**SEE:** https://github.com/behave/behave/blob/main/behave/model.py#L1344

**OTHERWISE:** On Example Table Generator(s)/Transformer(s)
The scenarios of a ScenarioOutline / Template are build lazily on first using `scenario_outline.scenarios`. 
When you are using `FileLocation(s)` (schema: `filename:line_number`), `behave` needs to mark any unused scenario as `SKIPPED`. Therefore, the ScenarioOutline/Template scenarios are build before any hook is called.
In addition, your functionality (reading the example table rows from a file) needs a preprocessor processing step that is currently missing in `behave`.

**Comment by jenisys** [comment]
No reaction => Close issue.
