### ISSUE TITLE
Scenario Outline is not expanding Example value when using filtering via `--name`

### ISSUE THREAD

**Issue by alexanderilyin** [behave/behave#1213]
# Context

I found a way to parametrize some of the test scenarios to increase functional coverage. Which currently 

```
6 features passed, 4 failed, 5 skipped
17 scenarios passed, 48 failed, 6 skipped
352 steps passed, 48 failed, 203 skipped, 0 undefined
Took 62m58.779s
```

My personal internal threshold for acceptable tests duration is 5 minutes and here I got myself a small problem.

One of the options to solve that issues is to horizontally scale tests execution with the help of external tools, where each isolated run will be looking like:

```
behave --quiet --no-skipped --no-summary --name='`pc render` command -- @3.5 Media Types: Object'
```

but it seems that it takes me to some unexplored grounds because it breaks Scenario Outline and Examples integration:

```
  Scenario Outline: `pc render` command -- @3.5 Media Types: Object 
    Given I am in "/tmp/sandbox/behave" directory                                                                                  # 0.014s
    Given I have temporary $HOME in "/tmp/sandbox/home"                                                                            # 0.014s
    Given a file named "partcad.yaml" does not exist                                                                               # 0.004s
    When I run "partcad -p /workspaces/partcad/examples render --package /produce_assembly_assy -t <type> -O ./ -a :logo_embedded" # 0.013s
    Then the command should exit with a status code of "0"                                                                         # 0.015s
      Traceback (most recent call last):
        File "/workspaces/partcad/.venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/workspaces/partcad/.venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/workspaces/partcad/features/steps/partcad-cli/commands/version.py", line 50, in step_impl
          assert context.result.returncode == int(exit_code)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError
      
      Captured logging:
      DEBUG:root:Created temporary workspace: /tmp/sandbox/behave/partcad-cli-otddojy2
      INFO:root:Created temporary home: /tmp/sandbox/home/partcad-cli-yfpb4y40
      DEBUG:root:Running command: partcad -p /workspaces/partcad/examples render --package /produce_assembly_assy -t <type> -O ./ -a :logo_embedded in /tmp/sandbox/behave/partcad-cli-otddojy2
      DEBUG:root:Command output: 
      DEBUG:root:Command error: /bin/sh: 1: cannot open type: No such file

    Then a file named "<filename>" should be created
    Given a file named "partcad.yaml" does not exist
    Then STDOUT should contain "DONE: Render: this:"
    Then STDOUT should not contain "WARN:"
```

Here is an example of the `.feature` implementation:

```cucumber
@cli @pc-render
Feature: `pc render` command

  Background: Sandbox
    Given I am in "/tmp/sandbox/behave" directory
    Given I have temporary $HOME in "/tmp/sandbox/home"
    Given a file named "partcad.yaml" does not exist

  Scenario Outline: `pc render` command
    When I run "partcad -p /workspaces/partcad/examples render --package /produce_assembly_assy -t <type> -O ./ -a :logo_embedded"
    Then the command should exit with a status code of "0"      
    Then a file named "<filename>" should be created
    Given a file named "partcad.yaml" does not exist
    Then STDOUT should contain "DONE: Render: this:"
    Then STDOUT should not contain "WARN:"

  @type-text
  Examples: Media Types: Text
    |    type | filename              |
    |  readme | README.md             |
```

Problem is that `<type>` is not expanded which leads to failure in the step.

# P. S.

- It would be nice to show time distribution for scenarios "box-and-whisker plot report" aka boxplot, here is example of what I'm talking about:
  - [Box Plot Explained: Interpretation, Examples, & Comparison](https://www.simplypsychology.org/boxplots.html)
  - Obviously it could be represent just as text but ascii art would be nice too, found few examples:
    - https://gitlab.com/Soha/termbox.py
    - https://github.com/ewheeler/ascii-boxplot

![image](https://github.com/user-attachments/assets/229e7a6c-e335-4f88-a7c7-d945216d473c)

# P. P. S.

Linking PR with the actual use cases: https://github.com/partcad/partcad/pull/208

**Comment by jenisys** [comment]
Which version of `behave` are you using ?

**Comment by alexanderilyin** [comment]
@jenisys seems that I'm using ["stable"](https://pypi.org/project/behave/1.2.6/):

```
⬢ [Docker] ❯ behave --version
behave 1.2.6
```

P. S. I can try current pre-release.

**Comment by jenisys** [comment]
Please retry the problem with `behave v1.2.7.dev6` (to avoid that we are trying to fix an already fixed problem).

```bash
# -- ALTERNATIVES:
$ pip3 install "behave==1.2.7.dev6"
$ pip3 install --pre behave
```

SEE ALSO:

* https://pypi.org/project/behave/1.2.7.dev6/

**Comment by alexanderilyin** [comment]
```
⬢ [Docker] ❯ poetry add behave --allow-prereleases
Using version ^1.2.7.dev6 for behave
...
  - Updating behave (1.2.6 -> 1.2.7.dev6): Installing...
```

Same problem with `<type>` not being replaced:

```
⬢ [Docker] ❯ behave --quiet --no-skipped --no-summary --name='`pc render` command -- @3.5 Media Types: Object'
USING RUNNER: behave.runner:Runner
...
@cli @pc-render
Feature: `pc render` command

  Background: Sandbox 

  @type-object
  Scenario Outline: `pc render` command -- @3.5 Media Types: Object 
    Given I am in "/tmp/sandbox/behave" directory                                                                                  # 0.013s
    Given I have temporary $HOME in "/tmp/sandbox/home"                                                                            # 0.012s
    Given a file named "partcad.yaml" does not exist                                                                               # 0.005s
    When I run "partcad -p /workspaces/partcad/examples render --package /produce_assembly_assy -t <type> -O ./ -a :logo_embedded" # 0.014s
    Then the command should exit with a status code of "0"                                                                         # 0.016s
      Traceback (most recent call last):
        File "/workspaces/partcad/.venv/lib/python3.11/site-packages/behave/model.py", line 1909, in run
          match.run(runner.context)
        File "/workspaces/partcad/.venv/lib/python3.11/site-packages/behave/matchers.py", line 104, in run
          self.func(context, *args, **kwargs)
        File "/workspaces/partcad/features/steps/partcad-cli/commands/version.py", line 50, in step_impl
          assert context.result.returncode == int(exit_code)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError
      
      Captured logging:
      DEBUG:root:Created temporary workspace: /tmp/sandbox/behave/partcad-cli-c9z4l0ec
      INFO:root:Created temporary home: /tmp/sandbox/home/partcad-cli-jq8nyahx
      DEBUG:root:Running command: partcad -p /workspaces/partcad/examples render --package /produce_assembly_assy -t <type> -O ./ -a :logo_embedded in /tmp/sandbox/behave/partcad-cli-c9z4l0ec
      DEBUG:root:Command output: 
      DEBUG:root:Command error: /bin/sh: 1: cannot open type: No such file

    Then a file named "<filename>" should be created
    Given a file named "partcad.yaml" does not exist
    Then STDOUT should contain "DONE: Render: this:"
    Then STDOUT should not contain "WARN:"
...
```

**Comment by alexanderilyin** [comment]
P. S.

> There is a broken link in release notes: [Gherkin v6 grammar](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp) ...

- https://behave.readthedocs.io/en/latest/new_and_noteworthy_v1.2.7/

**Comment by jenisys** [comment]
I provided a basic test for your issue.
But I cannot reproduce it (using the current version of `behave` or `behave v1.2.6`).

* ScenarioOutline placeholder replacement works fine in both cases.

SEE ALSO:

* [issue.features/issue1213.feature](https://github.com/behave/behave/blob/main/issue.features/issue1213.feature)

**Comment by alexanderilyin** [comment]
Thanks for taking a look, guess next step for me here is to run step it with debugger and see what's going on. I probably will do that in couple weeks from now, since I need to make one of the scaling solutions work.

**Comment by jenisys** [comment]
HINT:
* The ScenarioTemplate mechanism (aka: ScenarioOutline) renders the Scenarios before they are run. This step replaces the placeholders in the steps of the ScenarioOutline w/ their values from the Examples table row for each scenario.

SEE ALSO:

* [behave.model.ScenarioOutlineBuilder](https://github.com/behave/behave/blob/main/behave/model.py#L1254) class (and where it is used)

**Comment by alexanderilyin** [comment]
@jenisys I'm so sorry, it was Layer 8 problem:

```diff 
   @type-object
   Examples: Media Types: Object
+    |    type | filename              |
     |    step | logo_embedded.step    |
     |     stl | logo_embedded.stl     |
     |     3mf | logo_embedded.3mf     |
```
