### ISSUE TITLE
UnicodeDecodeError in tracebacks (when an exception is thrown in a step implementation)

### ISSUE THREAD

**Issue by karulis** [behave/behave#226]
OS: windows 8(polish)
python 2.7

Here is log:
  Scenario: run a simple test        # tutorial.feature:3
    Given we have behave installed   # steps\tutorial.py:4
    When we implement a test         # steps\tutorial.py:8
Traceback (most recent call last):
  File "c:\Python27\Scripts\behave-script.py", line 9, in <module>
    load_entry_point('behave==1.2.4', 'console_scripts', 'behave')()
  File "c:\Python27\lib\site-packages\behave__main__.py", line 111, in main
    failed = runner.run()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 659, in run
    return self.run_with_paths()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 680, in run_with_paths
    return self.run_model()
  File "c:\Python27\lib\site-packages\behave\runner.py", line 481, in run_model
    failed = feature.run(self)
  File "c:\Python27\lib\site-packages\behave\model.py", line 461, in run
    failed = scenario.run(runner)
  File "c:\Python27\lib\site-packages\behave\model.py", line 784, in run
    if not step.run(runner):
  File "c:\Python27\lib\site-packages\behave\model.py", line 1218, in run
    formatter.result(self)
  File "c:\Python27\lib\site-packages\behave\formatter\pretty.py", line 160, in result
    self.stream.write(indent(result.error_message.strip(), u'      '))
  File "c:\Python27\lib\site-packages\behave\textutil.py", line 29, in indent
    return newline.join([prefix + unicode(line) for line in lines])
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 11: ordinal not in range(128)

It is enough to implement step as:
@when('we implement a test')
def step_impl(context):
    raise Exception(chr(130))

This is only one of issues with unicode conversion, generaly problem accures when OS returns some error message.

**Comment by davidhrbac** [comment]
Can you release Behave with this fix?

**Comment by jenisys** [comment]
Planned approx. end of this month.

**Comment by davidhrbac** [comment]
Thanks, would be nice. We are also affected by this issue.
