### ISSUE TITLE
Behave json reports are incompatible with Cucumber ones

### ISSUE THREAD

**Issue by ghost** [behave/behave#267]
Howdy folks!

I've tried to make good looking reports from Behave with Cucumber-Reporting and surprise: Cukes json and Behave json files differ. Would be nice to produce Cucumber compatible json files from Behave just out-of-the-box:)

Best wishes.
Mike

**Comment by ChaitanyaChannella** [comment]
Hi,
I modified the cucumber html reports plugin source code to work with  behave,I'm currently trying to upload that to jenkins plugin area, in the mean time you can download it from https://github.com/ChaitanyaChannella/BehaveJenkinsPluginHPI.
Please note I haven't added support viewing results by tags.I'll do it in the coming weeks.

**Comment by ChaitanyaChannella** [comment]
To be able to use the plugin you need to displays the results in json format and use an outfile something like

behave  --format=json.pretty --outfile=results2.json,also attaching a screenshot on how the report looks like
![untitled](https://cloud.githubusercontent.com/assets/6221319/6353062/e11915b4-bc3e-11e4-973d-fb918fff3c0d.png)

**Comment by ChaitanyaChannella** [comment]
To be able to use the plugin you need to displays the results in json format and use an outfile something like

behave --format=json.pretty --outfile=results2.json,also attaching a screenshot on how the report looks like
![untitled](https://cloud.githubusercontent.com/assets/6221319/6353102/21d7e4c2-bc3f-11e4-80e5-ae6fa34250c5.png)

**Comment by Celinayang0101** [comment]
Hello ChaitanyaChannella ,
I want to generate the html report from local machine, could u pls provide your solution in a jar file or other package? Thanks a lot.

**Comment by jeremyjjbrown** [comment]
ChaitanyaChannella, do you mind putting the source in there? Unless i can see and I can build it myself I'm not going to install this on my Jenkins.

**Comment by jeremyjjbrown** [comment]
It would be nice if I could tell the teams I work with to use Behave so they can write acceptance tests in python. But if the only way to display the results in Jenkins is by using forks and patched versions of everything that's not going to happen. Visibility is the key! There is a nice section in the wiki on how Behave is the best, it will not be better than cucumber until I can at least just publish an html report from the upstream pip version. You've been given the code for html reports by Vadim that's sitting there for a year. Why?

**Comment by Celinayang0101** [comment]
I made the update myself and it works for me now. Thanks anyway.

**Comment by ChaitanyaChannella** [comment]
Celinayang0101 do let me know if you have any issues, Source code is in my github repository https://github.com/ChaitanyaChannella/BehaveJenkinsReporting

**Comment by ChaitanyaChannella** [comment]
Jeremy Brown,Source code is in my github repository
https://github.com/ChaitanyaChannella/BehaveJenkinsReporting, I have not
asked anyone to install this, as this is open source its at their own
discretion

**Comment by mixxorz** [comment]
I browsed the cucumber source code and found [this](https://github.com/cucumber/cucumber-ruby/blob/a94e2ae597b3cad583a7b12b9a755066072cb974/spec/cucumber/formatter/json_spec.rb).

Its the test they use for their JSON formatter. I think we can reverse engineer the cucumber spec for this.

**Comment by harshagv12** [comment]
Hi All,

I was working to generate the html report from json data. But  NullpointerException  error is seen show,

Build step 'Execute Windows batch command' marked build as failure
[BehaveReportPublisher] Compiling Behave Html Reports ...
ERROR: Build step failed with exception
java.lang.NullPointerException
	at net.jenkins.BehaveReportPublisher.perform(BehaveReportPublisher.java:63)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Build step 'Publish behave results as a report' marked build as failure
Finished: FAILURE

Below is the Json data,

[
{"status": "failed", "elements": [{"name": "Open practiceselenium.com website and fill the form to submit", "keyword": "Scenario", "tags": [], "steps": [{"result": {"status": "undefined", "duration": 0}, "step_type": "when", "name": "I open practiceselenium.com website", "keyword": "When", "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\cuccumber.feature:3"}, {"step_type": "when", "name": "I fill the form with values", "keyword": "And", "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\cuccumber.feature:4"}, {"step_type": "when", "name": "I hit submit button", "keyword": "And", "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\cuccumber.feature:5"}, {"step_type": "then", "name": "I go back to Welcome page and verify title", "keyword": "Then", "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\cuccumber.feature:6"}], "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\cuccumber.feature:2", "type": "scenario"}], "name": "Demonstrating WebElement operations", "keyword": "Feature", "tags": [], "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\cuccumber.feature:1"},

{"status": "passed", "elements": [{"name": "Add two numbers", "keyword": "Scenario", "tags": [], "steps": [{"name": "I have two integers a and b", "keyword": "Given", "step_type": "given", "result": {"status": "passed", "duration": 0.0019998550415039062}, "match": {"location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\steps\\first_behave.py:6", "arguments": []}, "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\first_behave.feature:4"}, {"name": "I add the numbers", "keyword": "When", "step_type": "when", "result": {"status": "passed", "duration": 0.0010001659393310547}, "match": {"location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\steps\\first_behave.py:12", "arguments": []}, "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\first_behave.feature:5"}, {"name": "I print the addition result", "keyword": "Then", "step_type": "then", "result": {"status": "passed", "duration": 0.0009999275207519531}, "match": {"location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\steps\\first_behave.py:17", "arguments": []}, "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\first_behave.feature:6"}], "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\first_behave.feature:3", "type": "scenario"}], "name": "My first behave feature", "keyword": "Feature", "tags": [], "location": "..\\..\\..\\..\\..\\..\\behave\\python_behave_template-master\\features\\first_behave.feature:1"}
]


Can anyone help me on this.

**Comment by andreybehalf** [comment]
Hi guys! 
I've written a little package which can help some of you guys ( It did helped me).
This package formats the behave json to cucumber json. Then you can use the new generated cucumber json to use on any plugins available for cucumber to generate prettier reports. (I've used it with [Cucumber-JVM Reporter](https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin))

The package can be found here: [Behave to Cucumber formatter](https://github.com/behalfinc/b2c/)

Hope this will help to some of you, good luck!

**Comment by luismesas** [comment]
Hi Andrey, whats the usage of the library after installing it?

**Comment by andreybehalf** [comment]
Hi @luismesas ,
The usage is simple you just need to import the b2c package into your code and pass your behave json as parameter to the convert() function. 
Here's is example to make it clear:
```

import json
import b2c

with open('behave_json.json') as behave_json:
    cucumber_json = b2c.convert(json.load(behave_json))
```

I will add this info to the README too, thanks!

P.S
I hope I will have time during this week to create python script to simplify it for people who don't want/need to integrate the library into their development and just want to re-format already existing behave jsons. The script will receive as argument a behave json file and will output a new cucumber json file.

**Comment by luismesas** [comment]
@andreybehalf that script would be great to integrate behave into CI pipelines

Thanks!

**Comment by pgm04** [comment]
Hi!.
@andreybehalf thank for your contribution. I added the library to my project in pycharm I am using behave and python. I created a new python file with the code that you wrote in previous post and it works , now in cucumber_json I have the new json in cucumber format.

Would you help me with the following steps? I don't know how to generate an HTML report with the new json. 

Sorry, I am new in this...
I would apreciate your help.

Thanks in advance,
Pamela.

**Comment by andreybehalf** [comment]
Hi @pgm04!
I'm using it to forward the generated .json to Cucumber Reports Plugin for Jenkins (You can download it [HERE](https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin))
From quick googling I found [THIS](https://www.npmjs.com/package/cucumber-html-report) tool which you might find useful.
Good luck!

**Comment by fredizzimo** [comment]
I just started to use Behave, and I was very surprised to see that there's no HTML output and that the JSON format is not compatible and even more surprised that this is an issue reported almost 2 years ago and still not fixed.

I then tried @andreybehalf's script, which worked OK for for some tests, but it wasn't nearly good enough to be able to generate valid JSON files for Behave's own test suite for example. The first issue I ran into was that things with multiple tags didn't work.

So I then copied the default json formatter, and started to modify it, [**and you can find the result here**](https://gist.github.com/fredizzimo/b92adf1d4596c0c1da1b05cc9899574b). At least from what I can see it now generates the correct reports for the Behave and Behave.examples tests. It has been tested with https://github.com/damianszczepanik/cucumber-reporting, and also a bit with https://github.com/leinonen/cucumber-html-report. The later has problems with the durations, but I didn't check it out further, since it also doesn't seem to support docstrings.

I decided to not make a pull request for two reasons. 

1. It's not registered as a built in formatter in behave, I just used it by passing the `--format` command line parameter
2. I didn't have time to make any tests, and I likely won't since I'm very busy, and have to go on with working on what I should be doing. The tests should at least cover the JSON specs that @mixxorz noticed. However they are incomplete and some things are missing, so I also had to look at the source code of https://github.com/damianszczepanik/cucumber-reporting to see what it expects. 

However, I hope that someone with more time in hands, could make this into a proper pull request. 

Here's a short summary of the main differences

1. The features and scenarios needed an"id" tag, basically the feature name in lowercase and spaces replaced by `-`
2. The features needed an `uri`, which is just the filename part of the `location`
3. Features, steps and scenarios need a `line`, probably also docstrings and tables
4. The `location` has been removed
5. Tags should have a `name` and a `line`, instead of being just strings
6. The background should be repeated before each scenario
7. `text` should be `docstring`
8. Tables have `rows` and `cols`
9. Duration should be reported as nanoseconds
10. The descriptions should be plain text, not list. I also added a html `<pre>`tag around them, because of [this](https://github.com/damianszczepanik/cucumber-reporting/issues/537). However that doesn't work when using https://github.com/leinonen/cucumber-html-report, so I suppose it should be something that is configurable. 

The only thing that  I can see is missing is hook support, but the formatters don't get notified about them at all, so it would have been very hard to implement. There are also other issues with the hooks too, and I will open another issue regarding that.

**Comment by jenisys** [comment]
@fredizzimo 
Can you explain why it should be necessary to copy the Background in front of each Scenario ?

NOTE: The background's steps are already contained in each scenario. The Background element exists only in JSON to allow you reverse engineer it into a feature file.

**Comment by fredizzimo** [comment]
@jenisys,

Because we run the backgrounds for each scenario, so each instance of it can have a different outcome. 

I guess it could have been designed in another way, if the reporting tools support it. But this is the way the cucumber does it, and therefore have to do it in the same way if we want to create compatible reports.

The alternative is to report the background once without any steps, and let the steps be included in the scenarios. The drawback of doing it that way, is that it's no longer possible to see which steps belongs to the background in reports, but it's a valid format and the reporting tools understand it.

On the other hand if the steps are included in the Background, and it's only reported once, then the outcome of those have to be faked. Otherwise the reporting tool will report the background and the steps as undefined, or not run. The step count for the statistics would also obviously be wrong.

BTW, I just quickly checked [Serenity (formerly Thucydides)](http://www.thucydides.info/#/), and it can actually import JSON files, but not cucumber ones. It however seems like it would be quite simple to generate JSON files compatible with that too. So that would probably be a good thing to look at for great looking and functional reporting.

**Comment by jenisys** [comment]
@fredizzimo 
As I have already said, the background steps are part of each scenario. Therefore, their outcome is reported with the scenario and not with the Background. When a background step fails, it causes its Scenario to fail and not the Background. Just make a feature with a Background and two Scenarios and look at the JSON output.

The Background mechanism is only a "writers help" with the intention: 
Include all my steps at the beginning of each Scenario.

And sorry, I disagree. By providing a Background you know that there is a background in this feature file (and which steps are part of it). Otherwise, you do not know this: the feature file could either have a Background or not (by manually copying the Background steps to each Scenario and keeping them in sync). Note that the Background only reports which steps are part of it but not their outcome.

**Comment by fredizzimo** [comment]
@jenisys 
I'm not taking any of the sides here, I think it's pointless in arguing which way is better when it's about something that we don't control. I just implemented the formatter according to the [best specifications that we have](https://github.com/cucumber/cucumber-ruby/blob/master/spec/cucumber/formatter/json_spec.rb). And reverse engineered a few other things from the cucumber reporting tool.

If you look at the specifications for "with a background", you can clearly see that the background is repeated several times, and the  steps are included in that one, not in the feature. It's true that both Behave and at least the ruby Cucumber implementation, but internally adds the steps to the feature, but that has nothing to do with the reporting.

Here's the description of the new formatter api, from the Ghit history, so if you want to argue with someone, argue with the ones that made that decision.
> Rewrite the Json formatter to use the new formatter api
Now the Json formatter will produce usable data for Scenario Outlines
also when not using the --expand option. All executed step will be
reported (that is background steps will be included each time they are
executed). Also hook executions will be reported. Remove the usage of
the Gherkin2 library.

Finally I'm not necessarily proposing that this Cucumber compatible formatter replaces the default one, it could be provided as an alternative. But first proper tests needs to be made, and make sure it handles everything. I don't think I have tested comments properly for example, hooks are also missing as I previously mentioned, and looking at that change I think the id for the scenario outlines are not correctly generated.

**Comment by carlosmmelo** [comment]
Hey @andreybehalf it seems the original `b2c` package was removed and no longer available.

I'm using https://github.com/luismesas/b2c in the mean time and its been able to convert it, however when trying to use the jenkkins cucumber report plugin it is saying the following error msg:

```net.masterthought.cucumber.ValidationException: File '/var/lib/jenkins/jobs/Acceptance_Test_Run/builds/12/cucumber-html-reports/.cache/cucumber_results.json' is not proper Cucumber report!```

Do you know if this b2c package is up to date with the one you have? trying to look for a workaround on this.

**Comment by fredizzimo** [comment]
@carlosmmelo, did you try to use the [cucumber_json formatter that I linked above](https://gist.github.com/fredizzimo/b92adf1d4596c0c1da1b05cc9899574b)? 

That one has been working great for me.

**Comment by carlosmmelo** [comment]
Oh, I overlooked that link for some reason. Let me give it a try @fredizzimo

**Comment by carlosmmelo** [comment]
@fredizzimo how would you integrate that script with behave? it doesnt look like its a converter but a formatter that would need to get behave source code to use this formatter?

**Comment by carlosmmelo** [comment]
so like you mentioned above, cucumber json does not like the behave json tags:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of net.masterthought.cucumber.json.Tag: no String-argument constructor/factory method to deserialize from String value ('authentication')
 at [Source: java.io.InputStreamReader@5b1368f7; line: 80, column: 7] (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["tags"]->java.lang.Object[][0])
```

**Comment by fredizzimo** [comment]
If you add it inside a folder named `formatters`,  you can run it with:
`behave --format=formatters.cucumber_json:PrettyCucumberJSONFormatter -o report_cucumber.json`

If you are using the master version of behave (1.2.6dev0), then it needs slight tweaking. I added another file to the gist that works with that.

**Comment by andreybehalf** [comment]
Hey guys,
We have moved the b2c project from Behalf's private repository to Behalf's OSS repository. 
The link to this repo [behalf-oss](https://github.com/behalf-oss/behave2cucumber)

Thanks.

**Comment by carlosmmelo** [comment]
Boooom!!! Thanks @andreybehalf that worked:

![image](https://cloud.githubusercontent.com/assets/5649650/24559879/59d05c62-160e-11e7-8118-bc71eb602117.png)

@fredizzimo for some reason I was always getting (having it inside a scripts dir instead of formatter like you proposed:

```
usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=scripts.cucumber_json:CucumberJSONFormatter is unknown
```

**Comment by fredizzimo** [comment]
@carlosmmelo, I believe you need to set the PYTHONPATH. See this issue https://github.com/behave/behave/issues/120

**Comment by carlosmmelo** [comment]
makes sense, Thanks @fredizzimo

**Comment by mpegjohn** [comment]
We have had a torrid time getting behave to work nicely with Jenkins.
We initially just tried the normal JSON output, that didn't work.
We tried parsing it using the behave2cucumber module, and that didn't work.
We then tried the formatter mentioned above, and behold! it worked.

In the past I have used perl pherkin and the output from that always parsed OK using Jenkins. Maybe the behave guys can take another look at this, as it is a real issue. Maybe just incorporate the formatter above.

**Comment by mpegjohn** [comment]
An issue I had trying to use the format=formatters.cucumber_json:CucumberJSONFormatter option, was that I needed to create a __init__.py file inside the formatters directory, to make it a python module.

Hope that helps someone.

**Comment by davidghiurco** [comment]
Can someone please help me figure out an easy way to convert behave jsons to standard cucumber jsons? I desperately need this functionality. I've been assigned to write a huge test suite and I need to pick a python BDD framework to work with. I'd like to use behave but the outputs of the test must be in valid cucumber.json format or else the automated reporter sciprts will crash and I don't have time to write a separate parser for behave json format.

Is the only solution right now using an unintegrated python script that I must get from an external source??

**Comment by MichelHeng** [comment]
@davidghiurco Like most of the people recommended here, I use behave in order to generate a json format report which I then convert using behave2cucumber package.

A quick example:
Saying that I'd like to run Test1.feature using behave, the bash command is:

  behave Test1.feature -f json.pretty -o Test1Result.json
  
As expected, Test1Result.json file contains a json output of your test result which is not usable by Cucumber Report. 

Converting the json report requires to use behave2cucumber package in a simple python script (10 lines of code?).

Once that's done, use the converted result files in your Cucumber Report plugin and it'll work flawlessly.

Hope this'll help.

**Comment by davidghiurco** [comment]
@MichelHeng I've actually already tried behave2cucumber and it seems to not be working properly. 

I ended up using radish instead of behave

**Comment by MichelHeng** [comment]
@davidghiurco In case this might help, I'm using:
- behave 1.2.5
- behave2cucumber 1.0.1
- Cucumber Report 3.7.0 specifying the JSON report location in the advanced section of the Cucumber Report configuration (in your project configuration)

And my script basically open() the Result.json file as inFile, then convert it:
   cucumber_result = behave2cucumber.convert(json.load(inFile)) 

And write cucumber_result in an outputFile.

I then feed my Jenkins project with these cucumber_result files.
If you ever want to give this another try.

**Comment by karthikcat** [comment]
@MichelHeng : U told just simple 10 lines of python script . i tried n no. of times but i wont succeed , instead of behave i tried with radish , when i run my feature file am getting error


error: location '$pwd/radish' to load modules does not exist

can some one plz me with this

**Comment by MichelHeng** [comment]
@karthikcat I think you may be mistaken as I don't use radish, I use behave with a converter to interpret the result files.

The 10 lines of python script could be like that:
convert2cucumber.py
```
import json
import behave2cucumber
import sys

fPath=str(sys.argv[1])
cucumber_json = None
with open(fPath) as behave_json:
    cucumber_json = behave2cucumber.convert(json.load(behave_json))

with open(fPath, "w") as of:
    json.dump(cucumber_json, of)
```

Quick example:
Feature File: Tuto01/tutorial01.feature

```
# file:features/tutorial01_basics.feature
Feature: Showing off behave (tutorial01)

Scenario: Run a simple test
    Given we have behave installed
    When we implement a test
    Then behave will test it for us!

```
I run the test using a script on jenkins (Build step, run shell script):

```
#!/bin/bash

  behave Tuto01/tutorial01.feature -f json.pretty -o json_reports/Tuto01.json
  python convert2cucumber.py json_reports/Tuto01.json

```

I then tell jenkins Cucumber reports advanced configuration to use the folder "json_reports" with the file include pattern "**/*.json" 

Sadly I cant' share my jenkins project configuration but it should be rather straightforward.
Hope you'll figure out how to fix your issue.

**Comment by karthikcat** [comment]
@MichelHeng : Thanks Man its works and thanks for ur Tym buddy :)

**Comment by davidghiurco** [comment]
@karthikcat all you need to do is specify the --basedir <directory name> flag in order to tell radish where to look for script implementations of the feature files. By default, if you do not provide that flag, it will be $pwd/radish. That is why you are getting that error. But all of this and more is in the official radish documentation :)

**Comment by manish-northout** [comment]
@s1ider  - Can you help me out about how do i use branch vrutkovs-html_formatter https://github.com/behave/behave/tree/vrutkovs-html_formatter
because seems while i install behve plugin in jenkins its not working correctly.

**Comment by jenisys** [comment]
Disable stale-bot here.

**Comment by illlych** [comment]
Converter *behave2cucumber* not well suited for Jenkins.
But fredizzimo cucumber:CucumberJSONFormatter works very well !
(see comment on 31 Mar 2017 by fredizzimo:
`behave --format=formatters.cucumber_json:PrettyCucumberJSONFormatter -o report_cucumber.json`
)
please include his https://gist.github.com/fredizzimo/b92adf1d4596c0c1da1b05cc9899574b
to \behave\formatter folder and 
add it to _builtins.py
 `   ("json.cucumber",  "behave.formatter.cucumber:CucumberJSONFormatter"),`

**Comment by bitcoder** [comment]
I made a small improvement to @fredizzimo work mentioned above for the serialization of Status infomation 
https://gist.github.com/bitcoder/9ca4f143a9ca1afa9fc55666c974f7c8 

By the way, if you're using Xray for test management in Jira, you can see here a tutorial detailing an example how to set this up: https://confluence.xpand-addons.com/display/XRAY/Testing+using+Behave+in+Python#TestingusingBehaveinPython-UsingCucumberJSONreports

**Comment by twiindan** [comment]
I have a problem using the @fredizzimo script. When I execute the test I'm obtaining the following error: TypeError: Object of type 'Status' is not JSON serializable. 

Anyone have the same problem?

**Comment by thayshiva** [comment]
Many thanks @andreybehalf . 
It works like charm.
All I did was installed behave2cucumber using pip3.
Then python3 -m behave2cucumber -i behave_json.json -o cucumber_json.json

**Comment by Krangster74** [comment]
Is there any traction on this? It would still be super useful to have a cucumber brand json output. Having used both the CucumberJVM and behave, the lack of "official cucumber" json hinders debuging due to the lack of information spun out of automated testing tools.

I understand there's no firm documentation on what cucumber json is but if there's multiple solutions as described above, it would be great to get one of them incorporated into the tool.

**Comment by ChandrashekarAppaji** [comment]
Hi Team,
may i know why am getting the below error:
**behave: error: format=cucumber_json:PrettyCucumberJSONFormatter is unknown**.
could you please help me , even after following the steps mentioned over here am unable to run my features.
Timeline activity: i copied cucumber_json.py  at the root folder and run the feature

**Comment by bitcoder** [comment]
@ChandrashekarAppaji you need to update your PYTHONPATH environment library to include the current path.

```
export PYTHONPATH=`pwd`

behave --format=cucumber_json:PrettyCucumberJSONFormatter -o cucumber.json  --format=json -o behave.json features/demo.feature
```

**Comment by ChandrashekarAppaji** [comment]
Hi @bitcoder 
Thanks for the reply, it really helped.
am able to generate the json!
With this i tried checking by importing the execution results in Xray-Jira manually [using the generated json] but sadly its throwing the error "There are no valid tests imported". I cross checked the Feature file and test on Jira ,there are no changes.
Can you please suggest any step that am missing

**Comment by bitcoder** [comment]
@ChandrashekarAppaji , this is a bit out-of-topic of this thread. If you're a Xray customer/trying out the product, you can use [Xray support](https://jira.xpand-it.com/servicedesk/customer/portal/2) to answer Xray related questions :)
Nevertheless, I can tell you in advance that your issue is described [here](https://confluence.xpand-it.com/pages/viewpage.action?pageId=46858243#TestinginBDDwithGherkinbasedframeworks(e.g.Cucumber)-SubmissionofCucumberresultssays%22Notestsfoundinexecutionresult%22). Basically, you have to follow one of the [workflows](https://confluence.xpand-it.com/pages/viewpage.action?pageId=46858243#TestinginBDDwithGherkinbasedframeworks(e.g.Cucumber)-Workflows) mentioned there; you can't just submit the results without having the Scenarios created in Xray. Anyway, this is not the proper place to discuss this :)

**Comment by ChandrashekarAppaji** [comment]
Ok Sure @bitcoder ,
Thanks for the suggestion, will try to follow the specified workflow.

**Comment by ChandrashekarAppaji** [comment]
Hi @bitcoder ,
am coming back with one question here :)
while executing the feature with formatter i see that there is no console output generated from the formatter which could be **script generated exception** or the **current step name** of the feature.
Could you please mention whether this is customized  according to our requirement if so?

**Comment by bitcoder** [comment]
Hi @ChandrashekarAppaji , I'm not sure that I've understood you. However, you can download the custom formatter and customize it accordingly to your needs. As far as I know, the custom formatter mentioned above does not write anything to STDOUT nor to STDERR.

**Comment by ChandrashekarAppaji** [comment]
Ok Thanks  for the reply @bitcoder :)

**Comment by writetomaha** [comment]
Team,

I tried creating the cucumber_json.py at the root folder, when i execute the below command i am getting this message. 

behave --format=cucumber_json:PrettyCucumberJSONFormatter -o cucumber.json  --format=json -o behave.json features/demo.feature

I have set the python path as well. 

usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=scripts.cucumber_json:CucumberJSONFormatter is unknown

Please help me in resolving this issue

**Comment by ralphavalon** [comment]
Just mentioning that now Cucumber has an official schema for Cucumber JSON report: https://github.com/cucumber/cucumber-json-schema/blob/main/schema.json

**Comment by blaisep** [comment]
> Just mentioning that now Cucumber has an official schema for Cucumber JSON report: https://github.com/cucumber/cucumber-json-schema/blob/main/schema.json

This is great! A few of us are getting together a work party to modernize the repo and also make it easier for the maintainers to review/approve PRs.

**Comment by zadigus** [comment]
When I follow [this advice](https://github.com/behave/behave/issues/267#issuecomment-321211333), I get it almost working up to a little detail: all steps in my background sections get a status "skipped", making all my scenarios inconclusive.

**Comment by bitcoder** [comment]
@zadigus ,have you tried [this solution](https://github.com/behave/behave/issues/267#issuecomment-375960052) ?
It produces a compatible Cucumber JSON report; I'm not sure if it covers well the use case you mentioned though.

**Comment by zadigus** [comment]
@bitcoder that's my next step, I will publish my findings here as soon as I have a result

**Comment by zadigus** [comment]
@bitcoder That looks good with the `cucumber_json:PrettyCucumberJSONFormatter`.

**Comment by bitcoder** [comment]
In [this repo](https://github.com/Xray-App/tutorial-python-behave) I have the cucumber json formatter mentioned earlier, and another slight variant I think for v1.2.6 of Behave.

**Comment by Johnlon** [comment]
Obviously since this conversation started there is a cucumber json schema now..
https://github.com/cucumber/cucumber-json-schema/blob/main/schema.json

**Comment by surbhimahendruai** [comment]
Even after below commands, I am getting error : behave: error: format=cucumber_json126:PrettyCucumberJSONFormatter is unknown
export PYTHONPATH=$(pwd)
behave --format=cucumber_json126:PrettyCucumberJSONFormatter -o results/cucumber.json  --format=json -o results/behave.json features

**Comment by jenisys** [comment]
@surbhimahendruai 
Use a newer `behave` version.
It provides you with better diagnostics what the problem is with: `ModuleNotFoundError, ClassNotFoundError, InvalidClassError, …`

SEE ALSO:
* [features/formatter.help.feature](https://github.com/behave/behave/blob/main/features/formatter.help.feature#L76) — BAD FORMATTERS section/rule
* Install a newer version of `behave` from the git repo: [behave docs: install — using-the-github-repository](https://behave.readthedocs.io/en/latest/install/#using-the-github-repository)
