### ISSUE TITLE
behave --lang-list fails on Python 3

### ISSUE THREAD

**Issue by pgkos** [behave/behave#309]
When I type ```behave --lang-list```, the following error occurs on Python 3.4:
```
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/behave/__main__.py", line 65, in main
    iso_codes.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```
probably the line 65 in ```__main__.py``` should be changed from
```
iso_codes.sort()
```
to
```
iso_codes = sorted(iso_codes)
```

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
