### ISSUE TITLE
Decorators should integrate better with other decorators

### ISSUE THREAD

**Issue by mcandre** [behave/behave#352]
To help my tests stay clean, I've written some decorators to ensure Kafka topics are clean before and after each of my tests run. I use my `@empty_topics` and `@empty_topics_after` decorators in my unit test suite as well as my BDD spec.

https://gist.github.com/mcandre/0e8722eddaef5e28bcb7

However, in order to use my decorator on method that also use a behave decorator (e.g., `@given` or `@then`), I need to remember to place my decorator before the behave decorator.

```
@empty_topics
@given('the topics are empty')
def the_topics_are_empty(self):
    self.container = MyContainer.construct()

@empty_topics_after
@then('Requests trickle from \'{request_topic}\' to \'{response_topic_success}\' and \'{response_topic_failure}\'')
def requests_trickle_from_to(self, request_topic, response_topic_success, response_topic_failure):
    requests = [Call(url='https://api.twitter.com/1.1/trends/available.json') for i in range(0, 10)]

    request_producer = Producer(container=self.container, topic=request_topic)

    # ...
```

works, but

```
@given('the topics are empty')
@empty_topics
def the_topics_are_empty(self):
    self.container = MyContainer.construct()

@empty_topics_after
@then('Requests trickle from \'{request_topic}\' to \'{response_topic_success}\' and \'{response_topic_failure}\'')
def requests_trickle_from_to(self, request_topic, response_topic_success, response_topic_failure):
    requests = [Call(url='https://api.twitter.com/1.1/trends/available.json') for i in range(0, 10)]

    request_producer = Producer(container=self.container, topic=request_topic)
```

complains:

```
$ behave
...
    Then Requests trickle from 'requests_twitter' to 'responses_twitter_success' and 'responses_twitter_failure'                                            # features/steps/steps.py:34 0.001s
      Traceback (most recent call last):
        File "/Users/andrew.pennebaker/.pyenv/versions/3.3.6/lib/python3.3/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/Users/andrew.pennebaker/.pyenv/versions/3.3.6/lib/python3.3/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "features/steps/steps.py", line 39, in requests_trickle_from_to
          request_producer = Producer(container=self.container, topic=request_topic)
        File "/Users/andrew.pennebaker/.pyenv/versions/3.3.6/lib/python3.3/site-packages/behave/runner.py", line 214, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'container'
```

Is there a way to write behave's decorators and/or my own decorators so that the wrapping order won't matter?

**Comment by jenisys** [comment]
I looked at your GIST to understand the implementation of ``@empty_topics`` decorators.

**Comment by mcandre** [comment]
@jenisys Thanks for taking a look. Could you help me tweak my decorator accordingly? I'm new to decorators, obviously.
