### ISSUE TITLE
Stacktrace will contain '\b' backspace character when running on windows

### ISSUE THREAD

**Issue by KevinOrtman** [behave/behave#366]
Because the behave module exists in the following directory, the traceback information on windows will always contain a '\b' character.  This is interpreted as a backspace character and provide erroneous output.  

    <python>\lib\site-packages\behave\model.py

When pretty formatted output is used in conjunction with JUnit, XML containing this special character is produced, which may break parser not expecting special characters in the data.

Example output 

```
  Scenario Outline: login to https://mysite.com/Login.aspx 
    Given a username "user" and a password "password"
    And I navigate to "https://mysite.com/Login.aspx"                      
      Traceback (most recent call last):
        File "C:\Anaconda\lib\site-packages\behave\model.py", line 1456, in run
          match.run(runner.context)
        File "C:\Anaconda\lib\site-packages\behave\model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "D:\source\stash\behave\webhelpers.py", line 7, in step_impl
          br.open(address)
        File "C:\Anaconda\lib\site-packages\mechanize\_mechanize.py", line 203, in open
          return self._mech_open(url, data, timeout=timeout)
        File "C:\Anaconda\lib\site-packages\mechanize\_mechanize.py", line 255, in _mech_open
          raise response
      httperror_seek_wrapper: HTTP Error 404: Not Found
```

**Comment by KevinOrtman** [comment]
This is a duplicate of #336
