### ISSUE TITLE
PYTHONPATH issue when executing Behave

### ISSUE THREAD

**Issue by jronald01** [behave/behave#368]
Getting the following when trying to include a source library in a behave run:

JAMERONA01M:hotelsbackend jamesr$ PYTHONPATH=/blah/blahblah:/blah/blahblah/src:$PYTHONPATH behave acceptance/features/my_feature.feature
Exception AttributeError: 'module' object has no attribute 'compile'
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 678, in run_with_paths
    self.load_step_definitions()
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 658, in load_step_definitions
    exec_file(os.path.join(path, name), step_module_globals)
  File "/Library/Python/2.7/site-packages/behave/runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "acceptance/features/steps/behave_test_steps.py", line 34, in <module>
    @given('the test "{test_name}" is initiated')
  File "/Library/Python/2.7/site-packages/behave/step_registry.py", line 85, in wrapper
    self.add_step_definition(step_type, step_text, func)
  File "/Library/Python/2.7/site-packages/behave/step_registry.py", line 50, in add_step_definition
    step_definitions.append(matchers.get_matcher(func, step_text))
  File "/Library/Python/2.7/site-packages/behave/matchers.py", line 225, in get_matcher
    return current_matcher(func, string)
  File "/Library/Python/2.7/site-packages/behave/matchers.py", line 72, in __init__
    self.parser = parse.compile(self.string, self.custom_types)
AttributeError: 'module' object has no attribute 'compile'

Our Developer traced it to the import in matchers.py.

**Changing line 4 in matchers.py fixed the issue for us:**
From:
```import parse```
To:
```from parse_type import parse```

That was all that was required to fix it.

**Comment by jenisys** [comment]
I assume you have another problem because the ``parse_type.parse`` is basically a copy of the ``parse`` module.

**Comment by jronald01** [comment]
Yeah, my bad, apologies - we did have another issue.
