### ISSUE TITLE
Can't run tagged scenario without providing the path to the feature file

### ISSUE THREAD

**Issue by kowalcj0** [behave/behave#373]
When I want to run scenarios with a certain tag then I'm getting error like this:

```python
behave -k  --stop -t 715
Using default path "./features"
Trying base directory: /home/user/git/mytests/features
Exception TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/user/.virtualenvs/wallet/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/model.py", line 492, in run
    run_feature = self.should_run(runner.config)
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/model.py", line 435, in should_run
    answer = self.should_run_with_tags(config.tags)
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/model.py", line 451, in should_run_with_tags
    if scenario.should_run_with_tags(tag_expression):
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/model.py", line 1200, in should_run_with_tags
    for scenario in self.scenarios:     # -- REQUIRE: BUILD-SCENARIOS
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/model.py", line 1159, in scenarios
    self._scenarios = builder.build_scenarios(self)
  File "/home/user/.virtualenvs/wallet/local/lib/python2.7/site-packages/behave/model.py", line 1035, in build_scenarios
    for row_index, row in enumerate(example.table):
TypeError: 'NoneType' object is not iterable
```

but when I provide the whole path to the feature file and the same tag, all is good:

```bash
behave -k features/some.feature  --stop -t 715
Supplied path: "features/some.feature"
Primary path is to a file so using its directory
Trying base directory: /home/user/git/mytests/features
Feature: Feature name #
 features/some.feature:1
  or list the product groups
  @2 @bug @715 @fixme
  ....
  ....
```

I'm using `behave==1.2.5` on Linux Mint 17.2 x64 3.13.0-37-generic with Python 2.7.6

Thanks

**Comment by jenisys** [comment]
Your first stack trace hints (last line) that you have a faulty "Scenario Outline" (without an example table => None):

* without an "Examples:" section (PROBABLE PROBLEM CAUSE)
* with a faulty "Examples:" section (table problem)

Normally the parser should catch this problem (or the model code should be able to cope with it).
Maybe nobody has stumbled over this syndrome yet.

@kowalcj0 
If my assumption is correct change change the title of the issue accordingly (or close this issue and open a new one with correct title).

**Comment by kowalcj0** [comment]
I'm investigating this now. Thank you @jenisys for your hint.

**Comment by kowalcj0** [comment]
I've found the faulty scenario.
It was a simple copy/paste issue. Scenario had 2 `Examples` sections:

```
Examples: Some examples
Examples: Another examples
    |field1   |field2 |....
    ....
```

It'd be definitely helpful to catch such case and print out for example name of the scenario and/or the path of the invalid feature file.
Apart from that I think we should close this ticket.

Thank you @jenisys

**Comment by jenisys** [comment]
Should be resolved.
