### ISSUE TITLE
Execution of scenario outline stops on first error

### ISSUE THREAD

**Issue by PiotrNestor** [behave/behave#413]
Behave: 1.2.5
The execution of scenario outline stops on first error. I would expect that all example variants should be executed irrelevant if any of them fails.

Example:
Gherkin scenario outline
```
Feature: Cucumber

@wip
Scenario Outline: Outlined given, when, then
Given there are <start> cucumbers
When I eat <eat> cucumbers
Then I should have <left> cucumbers

Examples:
| start | eat | left |
|  12   |  5  |  7   |
|  12   |  5  |  12  |
|  13   |  13 |  0   |
```

Python step implementation:
```python
from behave import Given, When, Then

@Given('there are {start} cucumbers')
def start_cucumbers(context, start):
    context.start = start


@When('I eat {eat} cucumbers')
def eat_cucumbers(context, eat):
    context.eat = eat


@Then('I should have {left} cucumbers')
def should_have_left_cucumbers(context, left):
    assert int(context.start) - int(context.eat) == int(left)
```

**Running the above results**
```
Feature: Cucumber

  Scenario Outline: Outlined given, when, then -- @1.1 
    Given there are 12 cucumbers ... passed in 0.000s
    When I eat 5 cucumbers ... passed in 0.000s
    Then I should have 7 cucumbers ... passed in 0.000s

  Scenario Outline: Outlined given, when, then -- @1.2 
    Given there are 12 cucumbers ... passed in 0.000s
    When I eat 5 cucumbers ... passed in 0.000s
    Then I should have 12 cucumbers ... failed in 0.000s
Traceback (most recent call last):
  File "C:\Python27\lib\site-packagesehave\model.py", line 1456, in run
    match.run(runner.context)
  File "C:\Python27\lib\site-packagesehave\model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features\steps\ex.py", line 15, in should_have_left_cucumbers
    assert int(context.start) - int(context.eat) == int(left)
AssertionError



Failing scenarios:
  features\outline.feature:12  Outlined given, when, then -- @1.2
```
**The following is NOT executed but it should**
  Scenario Outline: Outlined given, when, then -- @1.3

**Comment by PiotrNestor** [comment]
OK, This is not a problem but just a feature :)
The @wip tag by default will set the runner to stop on first error.

This issue can be closed.
