### ISSUE TITLE
'Number' not recognized for User-defined Data Type 

### ISSUE THREAD

**Issue by rehmanzile** [behave/behave#421]
When I run [User-defined Data Type ](https://jenisys.github.io/behave.example/tutorials/tutorial10.html) scenario using **python 3.5.1**, I am getting following error:

$ behave tutorial10_step_usertype.feature 
Exception ValueError: type 'Number' not recognised
Traceback (most recent call last):
  File "/Users/zile/dev/bin/behave", line 9, in <module>
    load_entry_point('behave==1.2.6.dev0', 'console_scripts', 'behave')()
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/__main__.py", line 115, in main
    failed = runner.run()
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/runner.py", line 758, in run
    return self.run_with_paths()
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/runner.py", line 764, in run_with_paths
    self.load_step_definitions()
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/runner.py", line 743, in load_step_definitions
    exec_file(os.path.join(path, name), step_module_globals)
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/runner.py", line 354, in exec_file
    exec(code, globals_, locals_)
  File "steps/tutorial10.py", line 9, in <module>
    @when('I add "{x:Number}" and "{y:Number}"')
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/step_registry.py", line 82, in wrapper
    self.add_step_definition(step_type, step_text, func)
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/step_registry.py", line 49, in add_step_definition
    step_definitions.append(get_matcher(func, step_text))
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/matchers.py", line 371, in get_matcher
    return current_matcher(func, string)
  File "/Users/zile/dev/lib/python3.5/site-packages/behave/matchers.py", line 214, in __init__
    self.parser = parse.compile(self.string, self.custom_types)
  File "/Users/zile/dev/lib/python3.5/site-packages/parse.py", line 1105, in compile
    return Parser(format, extra_types=extra_types)
  File "/Users/zile/dev/lib/python3.5/site-packages/parse.py", line 627, in __init__
    self._expression = self._generate_expression()
  File "/Users/zile/dev/lib/python3.5/site-packages/parse.py", line 758, in _generate_expression
    e.append(self._handle_field(part))
  File "/Users/zile/dev/lib/python3.5/site-packages/parse.py", line 824, in _handle_field
    format = extract_format(format, self._extra_types)
  File "/Users/zile/dev/lib/python3.5/site-packages/parse.py", line 596, in extract_format
    raise ValueError('type %r not recognised' % type)
ValueError: type 'Number' not recognised

Is there something wrong with my environment is it is related to the latest version of python interpreter? Please advise.

**Comment by jenisys** [comment]
You opening an issue in the wrong repository. You should use [jenisys/behave.example](https://github.com/jenisys/behave.example). But there was a fix after [issue2](https://github.com/jenisys/behave.example/issues/2) related to Python3 that was not supported before.
behave.example works fine with Python3.5 (I just checked again). 

Have you use the current HEAD of [jenisys/behave.example](https://github.com/jenisys/behave.example) ?

**Comment by TageNielsen** [comment]
I ran into the same issue following the examples directly.   The solution for the problem is implementing the snippet shown in [Type Definition Basics](https://behave.github.io/behave.example/datatype/basics.html),  but not shown in step [Tutorial 10: User-defined Data Type](https://behave.github.io/behave.example/tutorials/tutorial10.html).     Not a bug.

**Comment by jenisys** [comment]
That may be true, but the Git repository contains the complete example(s). 
Therefore, I always know that my (documented) examples work. I can run them (for the three chapters). Note that the documentation itself uses the example files directly and runs ``behave`` when the HTML documentation is built. By making it (too) simple, maybe I have made it complicated for some people :smirk:.

I would normally expect the people to be lazy and use the provided examples and fiddle around with them instead of reproducing it from the documentation. 

AS A SMALL SEARCH SHOWS (with ``pss`` as grep-like tool, searching in python files):
```shell
$ cd behave.example/features
$ pss --py Number
...
./steps/step_tutorial10.py
12:    Examples: Add Numbers
30:    :return: Number instance (integer), created from parsed text.
34:register_type(Number=parse_number)
48:@when('I add "{x:Number}" and "{y:Number}"')
54:@then('the calculator returns "{expected:Number}"')
...
```

QUESTION @rehmanzile: 
Did you reproduce the example from the documentation or did you use the example from the Github repository ?

**Comment by rehmanzile** [comment]
I produced the example from documentation. I am trying to get the rest of my team to learn about BDD and these tutorials are really helpful! Whatever you can do to make it easy for others to learn would be greatly appreciated!

Thanks,
Zile Rehman

**Comment by jenisys** [comment]
@rehmanzile @TageNielsen 
I updated the documentation page in the "behave.example" project. Type specification and "Complete picture" is now shown for tutorial10 (in the latest version of the project).

**Comment by buildmaster-nyansa** [comment]
Awesome. Thanks!

**Comment by rehmanzile** [comment]
Awesome! Thanks.
