### ISSUE TITLE
after_scenario HOOK-ERROR asserts with jUnit reporter

### ISSUE THREAD

**Issue by lagin** [behave/behave#466]
Hi, with 1.2.6, I am able to assert and fail scenario in after_scenario, but there is a problem while reporting with jUnit reporter, see Traceback.

Do you plan to support this?

```
HOOK-ERROR in after_scenario: AssertionError: MSG
```

```
Traceback (most recent call last):
Exception AssertionError: OOPS: No failed step found in scenario: Scenario
  File "C:\python34\scripts\behave-script.py", line 9, in <module>
    load_entry_point('behave==1.2.6.dev0', 'console_scripts', 'behave')()
  File "C:\Python34\lib\site-packages\behave\__main__.py", line 115, in main
    failed = runner.run()
  File "C:\Python34\lib\site-packages\behave\runner.py", line 758, in run
    return self.run_with_paths()
  File "C:\Python34\lib\site-packages\behave\runner.py", line 779, in run_with_paths
    return self.run_model()
  File "C:\Python34\lib\site-packages\behave\runner.py", line 579, in run_model
    reporter.feature(feature)
  File "C:\Python34\lib\site-packages\behave\reporter\junit.py", line 138, in feature
    self._process_scenario(scenario, report)
  File "C:\Python34\lib\site-packages\behave\reporter\junit.py", line 275, in _process_scenario
    assert step, "OOPS: No failed step found in scenario: %s" % scenario.name
AssertionError: OOPS: No failed step found in scenario: Scenario
```

**Comment by jenisys** [comment]
@lagin 
I will look at it in detail. 
But seems to be just a sanity check in the Unit reporter. Should be fixed to match the changed assumptions.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0
