### ISSUE TITLE
Option to have @capture decorator output to log file instead of print

### ISSUE THREAD

**Issue by sanseihappa** [behave/behave#486]
It would be nice to have the `@capture` decorator (http://pythonhosted.org/behave/api.html#behave.log_capture.capture) take an optional argument to log to a file instead of printing.

This would allow for easily instrumenting the environment file functions without making them obtrusive to the console output.

**Comment by sanseihappa** [comment]
I've put in place a workaround to allow this in my local usage of the behave package, but am now running into a UnicodeDecodeError:

```
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 919, in run
    runner.run_hook('after_scenario', runner.context, self)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "/mnt/work/test/lib/logcapture.py", line 22, in f
    v = h.getvalue()
  File "/usr/local/lib/python2.7/dist-packages/behave/log_capture.py", line 99, in getvalue
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3807: ordinal not in range(128)
```

@jenisys Should I file a separate issue for this?

**Comment by jenisys** [comment]
@sanseihappa 
Yes, add a new issue for the log_capture UnicodeDecodeError problem. Provide some info which encoding or language locale your are using, etc. (But the problem may be caused by our code).

**Comment by jenisys** [comment]
@sanseihappa 
I looked at the description of ``@capture`` again.
The requested feature goes against the intention of the decorator.

But if you think it is useful, provide the implementation for yourself (and maybe others).
That should not be difficult by providing an adapted implementation of the ``@capture`` decorator.
