### ISSUE TITLE
log_capture UnicodeDecodeError

### ISSUE THREAD

**Issue by sanseihappa** [behave/behave#495]
Related to #486.

Added a modified ``@capture`` decorator and now seeing a UnicodeDecodeError:

```python
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 483, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 523, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 919, in run
    runner.run_hook('after_scenario', runner.context, self)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "/mnt/work/test/lib/logcapture.py", line 22, in f
    v = h.getvalue()
  File "/usr/local/lib/python2.7/dist-packages/behave/log_capture.py", line 99, in getvalue
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3807: ordinal not in range(128)
```

Here is the code snippet of the modified decorator:

```python
import functools

from behave.log_capture import LoggingCapture

import lib.utils as utils
import lib.constants as constants


def capture(*args, **kw):
    """Logging capture decorator.

    This is a clone of the capture call in behave.log_capture, but modified to allow logging
    to a file instead of printing.
    """
    def create_decorator(func, level=None):
        def f(context, *args):
            h = LoggingCapture(context.config, level=level)
            h.inveigle()
            try:
                func(context, *args)
            finally:
                v = h.getvalue()
                if v:
                    utils.create_data_directory()
                    with open("{0}/behave_environment.log".format(constants.DATA_DIRECTORY), "a") as fh:
                        fh.write('Captured Logging ({0}):\n{1}\n{2}\n\n'.format(func.__name__, str("=" * 80), v))
                h.abandon()
        return f

    if not args:
        return functools.partial(create_decorator, level=kw.get('level'))
    else:
        return create_decorator(args[0])
```

Using:

```python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'UTF-8')
>>> 
```

**Comment by jenisys** [comment]
@sanseihappa 
Try the following: 
Add a encoding-declaration to your python files (that cause the problem).
Verify if this solves the problem.

BACKGROUND: 
If you do not specify an encoding-declaration in Python2, it assumes ASCII.
ASCII causes problems when you are not working correctly with unicode string.
Implicit unicode encode/decode steps occur that use the ASCII encoding.

**EXAMPLE:**
```python
# -*- coding: UTF-8 -*-
# FILE: features/environment.py
...
```

Otherwise: 
Check what gets stored in ``LogCapture.buffer`` attribute (like: ``print(repr(h.buffer))``).
Inspect it (or print it) before ``h.getvalue()`` gets called.

**Comment by jenisys** [comment]
@sanseihappa 
I just verified my hint from above (regarding the encoding-declaration).
I have setup a simple unittest with pytest. When I remove the encoding-declaration from the beginning of the test file, I run into similar problems / similar traceback. When I readd it, everything is fine. Note that I used the original capture decorator.

**Comment by sanseihappa** [comment]
I tracked this down to a string being logged in a supporting library.  That library is receiving bytes off the network and wasn't handling the possibility that a non-UTF-8 character could exist in the contents.

Thanks for the tip to examine the LogCapture.buffer, this led me down the path to discover the offending library logging.
