### ISSUE TITLE
behave -n anything crashes with "ValueError: cannot use LOCALE flag with a str pattern"

### ISSUE THREAD

**Issue by dschweisguth** [behave/behave#536]
```
> python --version
Python 3.6.0
> behave --version
behave 1.2.5
> behave -n anything
Traceback (most recent call last):
  File "/Users/dave/.pyenv/versions/3.6.0-api/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/Users/dave/.pyenv/versions/3.6.0/envs/3.6.0-api/lib/python3.6/site-packages/behave/__main__.py", line 53, in main
    config = Configuration(args)
  File "/Users/dave/.pyenv/versions/3.6.0/envs/3.6.0-api/lib/python3.6/site-packages/behave/configuration.py", line 601, in __init__
    self.name_re = self.build_name_re(self.name)
  File "/Users/dave/.pyenv/versions/3.6.0/envs/3.6.0-api/lib/python3.6/site-packages/behave/configuration.py", line 665, in build_name_re
    return re.compile(pattern, flags=(re.UNICODE | re.LOCALE))
  File "/Users/dave/.pyenv/versions/3.6.0/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/dave/.pyenv/versions/3.6.0/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/dave/.pyenv/versions/3.6.0/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/dave/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/Users/dave/.pyenv/versions/3.6.0/lib/python3.6/sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

I didn't check other Python versions. behave in general and `behave -i` works fine in my environment.

**Comment by jenisys** [comment]
Use the current HEAD of the github repository. It was already fixed in the repository before Python 3.6 came out. The tests on Travis were stumbling over the same problem.

That was one of the changes in Python 3.6 regular expressions how the LOCALE flag is handled. For example, your behave version should work on Python 3.5.2.

SEE ALSO:
* [travis-ci:behave builds with Python 3.6](https://travis-ci.org/behave/behave/builds/199000740)

**Comment by dschweisguth** [comment]
Confirmed that current HEAD fixes the issue for me. Thanks for your hard work!

**Comment by johanvergeer** [comment]
Current HEAD is working for me as well. 
Thanks for the update.

**Comment by YadvinderChauhan** [comment]
Hi, I am a tester and currently learning selenium Python and trying to use the Python Behave test automation framework. I am following a very basic test following instructions documented at http://www.seleniumframework.com/python-basic/first-behave-step/ . At step 4 of this page I get the following:

Testing started at 11:57 ...
C:\Users\chauhany\PycharmProjects\Subscriptions\Scripts\python.exe "C:\Users\chauhany\AppData\Roaming\JetBrains\PyCharm 2017.3\helpers\pycharm\behave_runner.py"
Traceback (most recent call last):
  File "C:\Users\chauhany\AppData\Roaming\JetBrains\PyCharm 2017.3\helpers\pycharm\behave_runner.py", line 285, in <module>
    my_config = configuration.Configuration(command_args=command_args)
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\site-packages\behave\configuration.py", line 593, in __init__
    self.name_re = self.build_name_re(self.name)
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\site-packages\behave\configuration.py", line 635, in build_name_re
    return re.compile(pattern, flags=(re.UNICODE | re.LOCALE))
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "C:\Users\chauhany\PycharmProjects\Subscriptions\lib\sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern

Process finished with exit code 1

As I am new in this game, I do not understand what 'Current HEAD' means as some authors have suggested here. I would appreciate if I could get some direction here and steps to fix my issue. Many thanks.

**Comment by johanvergeer** [comment]
@YadvinderChauhan HEAD means the latest version in the git repository.   

So instead of using the command `pip install behave`, which install the latest version that was released on Pypi, you will need to use a command that will get the latest version from Github, which is more up-to-date then the Pypi version. 

You can still use the `pip` command to install the bahave package, but to get it from Github instead of Pypi you'll need to tell `pip` where to get it. Therefore you can use `pip install git+https://github.com/behave/behave` which will get the latest version from the git repository at Github and install it on or machine.

**Comment by YadvinderChauhan** [comment]
@johanvergeer. Thanks you for your prompt response and instruction. However, on running the pip install git+https://github.com/behave/behave command from the command prompt I get 'Cannot find command 'git' error.  see screenshot.
![error](https://user-images.githubusercontent.com/13240355/33934899-1648a20c-dff2-11e7-9b58-f66be6ebae1d.png)

**Comment by jenisys** [comment]
@YadvinderChauhan 
Note that you need to have git installed or in the search-path under Windows.

As alternative: 
* Download the ZIP archive from the Github project page (green button "Clone or download" on project page).
* Unpack the ZIP archive on your PC
* Open "cmd" shell where the behave "setup.py" is and run "pip install ." or "python setup.py install".

SEE ALSO:
* https://github.com/behave/behave
* [behave/docs/install.rst](https://github.com/behave/behave/blob/master/docs/install.rst#using-the-github-repository)

**Comment by YadvinderChauhan** [comment]
@jenisys. Thank you for the instructions. You guys are really helpful.
