### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by msabramo** [behave/behave#587]
I'm wondering if there are plans to do a new release to PyPI soon, since the last release (1.2.5) was back in 2015.

In particular, I am interested in having a release with this fix:

https://github.com/behave/behave/commit/f52cc2f59df8e21a5caf21b268bbd9ca6fa3e1e1

as whenever I try to use `--name` in Python 3.6, I get:

```python
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 53, in main
    config = Configuration(args)
  File "/usr/local/lib/python3.6/site-packages/behave/configuration.py", line 601, in __init__
    self.name_re = self.build_name_re(self.name)
  File "/usr/local/lib/python3.6/site-packages/behave/configuration.py", line 665, in build_name_re
    return re.compile(pattern, flags=(re.UNICODE | re.LOCALE))
  File "/usr/local/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.6/sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/local/lib/python3.6/sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

**Comment by Xuanwo** [comment]
Same here, I want a new release to fix a table problem.

**Comment by MonkeyFinger** [comment]
Same here, need to get Junit report + Userdata from behave.ini file working in the same release

**Comment by chrono** [comment]
https://github.com/behave/behave/issues/490#issuecomment-253983627

**Comment by ouchxp** [comment]
![please-kitten-picture](https://user-images.githubusercontent.com/1253729/30888060-eda929b0-a37a-11e7-8ee2-9066c3247e8b.jpeg)

**Comment by jenisys** [comment]
It is in the works and it looks like I am having a long weekend ... (to work on it).
So please wait until middle or end of next week.
NOTE: Pip supports also to install from the Github repository (and I know a stable version is better).

**Comment by JPvRiel** [comment]
Appreciate it's not simple finding time to get a new stable release out.

I suppose we can simply download and run 1.26dev0 test suite to understand what might be still need work and if it's okay to risk running 1.26dev0 in the meantime?

I guessing there's no know list of regressions/issues with 1.26? Might be good to run the tests and list the failures in this issue so people can gauge what still needs doing and help out - then maybe tag issues on github as 1.26 release blockers...

**Comment by PascalLeMerrerPro** [comment]
Any news?

**Comment by lganet** [comment]
Waiting too.

**Comment by LJBD** [comment]
Hello, @jenisys!

Are there any new estimates as to when a new version might be released? Or a TODO list of things that you want to get done before that happens?

**Comment by LJBD** [comment]
Hooray, thanks @jenisys !

**Comment by jenisys** [comment]
:smile:

**Comment by andreypetrenko82** [comment]
Hooray!!! I've been waiting this so long :) Hooray :)
