### ISSUE TITLE
UnicodeEncodeError when using non-ascii symbols.

### ISSUE THREAD

**Issue by Glazz87** [behave/behave#590]
I use Python 3.5.2, behave 1.2.5 on Windows 7.

This code make http request which contains some russian symbols:

```
from requests import request

payload = '''
{
	"stub" :
	{
		"data" : {
			"terminal_address" : "Москва",
			"agent_support_phone" : "8-888-88-88-88",
			"is_success" : true,
			"mf_retail" : true,
			"result" : 1
		}
	}
}
'''.encode('utf-8')

response = request('POST',
                            'http://127.0.0.1:1234/rules',
                            data=payload,
                            headers={"content-type": "application/json"})
```

And this works pretty good: web server saves this "stub" and i see in DB exactly what i sent:
```
{
	"stub" :
	{
		"data" : {
			"terminal_address" : "Москва",
			"agent_support_phone" : "8-888-88-88-88",
			"is_success" : true,
			"mf_retail" : true,
			"result" : 1
		}
	}
}
```

But if i put this code into before_all() hook cyrillic symbols will be corrupted, so i'll see in DB following:

```
{
	"stub" :
	{
		"data" : {
			"terminal_address" : "РњРѕСЃРєРІР°",
			"agent_support_phone" : "8-888-88-88-88",
			"is_success" : true,
			"mf_retail" : true,
			"result" : 1
		}
	}
}
```

UnicodeEncodeError exception catched:
```
Exception UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 112: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\pirojok\AppData\Local\Programs\Python\Python35-32\lib\runpy.py",
 line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pirojok\AppData\Local\Programs\Python\Python35-32\lib\runpy.py",
 line 85, in _run_code
    exec(code, run_globals)
  File "C:\Git\new-ssk-ui\venv\Scripts\behave.exe\__main__.py", line 9, in <module>

  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\__main__.py", line 109, in
main
    failed = runner.run()
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\runner.py", line 672, in ru
n
    return self.run_with_paths()
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\runner.py", line 693, in ru
n_with_paths
    return self.run_model()
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\runner.py", line 483, in ru
n_model
    failed = feature.run(self)
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\model.py", line 523, in run

    failed = scenario.run(runner)
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\model.py", line 882, in run

    if not step.run(runner):
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\model.py", line 1508, in ru
n
    formatter.result(self)
  File "c:\git\new-ssk-ui\venv\lib\site-packages\behave\formatter\pretty.py", line
164, in result
    self.stream.write(indent(result.error_message.strip(), u'      '))
  File "C:\Users\pirojok\AppData\Local\Programs\Python\Python35-32\lib\encodings\
cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 112
: character maps to <undefined>
```

**Comment by Glazz87** [comment]
I investigated this strange behavior and found that this cause with any code contains cyrillic symbols that executed by behave: before_all/after_all hooks, step implementation functions and so on. This happens not only with requests, but with any code contains cyrillic symbols, even simple print('Москва'). Exactly this code, executed without behave works normally.

Fortunatelly 1.2.6dev0 version doesn't contain this bug.

**Comment by jenisys** [comment]
AFAIK, behave-1.2.5 requires environment files to use UTF-8 encoding (and or encoding-hint), like

```python
# -*- coding: UTF-8 -*-
# FILE: features/environment.py

def before_all(context):
    pass
```

**Comment by Glazz87** [comment]
In python3 utf-8 is deafault encoding and i didn't change it. However even if i explicitly type "# -*- coding: UTF-8 -*-" it doesn't eliminate error for behave 1.2.5.
