### ISSUE TITLE
Stack traceback when trying to list available languages

### ISSUE THREAD

**Issue by alenmeister** [behave/behave#604]
Run from Powershell on Windows 10 with Python 3.6.2 and Behave 1.2.5:

```
PS C:\Users\H804288\Projects\eika-automation-test> behave --lang-list
Traceback (most recent call last):
  File "c:\users\h804288\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\h804288\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\H804288\AppData\Local\Programs\Python\Python36\Scripts\behave.exe\__main__.py", line 9, in <module>
  File "c:\users\h804288\appdata\local\programs\python\python36\lib\site-packages\behave\__main__.py", line 65, in main
    iso_codes.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

**Comment by spyoungtech** [comment]
This is not a problem in v1.2.6.dev0.

    $ behave --version
    behave 1.2.6.dev0
    $ behave --lang-list
    Languages available:
    ar: العربية / Arabic
    bg: български / Bulgarian
    ca: català / Catalan
    # etc

**Comment by alenmeister** [comment]
What's the current ETA on v1.2.6?
