### ISSUE TITLE
TypeError in formatter/pretty.py print_step

### ISSUE THREAD

**Issue by evanjtravis** [behave/behave#669]
- Python 3.5
 - Behave 1.2.6
 - Running behave using virtualenv
 - Using the default step parser and registering a handful of custom variable types.

The module throws a TypeError when it comes across the following step:
```@given(u"terraform '{object_type:Value}' with name '{name:Name}'"```

The exact line it breaks on is 290: ```for arg in arguments"```, 'NoneType' object is not iterable.

The step is imported along with every other step in its module into step file *A*. Importing other step files into step file *A* does not introduce this error. ```behave --dry-run -f steps``` works just fine and prints out the step, but actually running the tests seems to trip the engine up.

The text printed to stdout:
```
$ behave features/
Feature: Typical instances of the ecr module. # features/basic.feature:1

  Background: Basic setup  # features/basic.feature:3

  Scenario: Bare bones plan                                                           # features/basic.feature:10
    Given Exception TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ejtravis/workspace/cloudfirst/fork/env/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/runner.py", line 804, in run
    return self.run_with_paths()
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/runner.py", line 824, in run_with_paths
    return self.run_model()
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/runner.py", line 626, in run_model
    failed = feature.run(self)
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/model.py", line 321, in run
    failed = scenario.run(runner)
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/model.py", line 711, in run
    if not step.run(runner):
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/model.py", line 1311, in run
    formatter.match(match)
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/formatter/pretty.py", line 132, in match
    self._match.location, self.monochrome)
  File "/home/ejtravis/workspace/cloudfirst/fork/env/lib/python3.5/site-packages/behave/formatter/pretty.py", line 290, in print_step
    for arg in arguments:
TypeError: 'NoneType' object is not iterable
```

**Comment by evanjtravis** [comment]
For the `behave.matchers.Match` class, `self.arguments` is initialized to `None` by default. I changed this to instead initialize as an empty list. There is no longer a TypeError, but behave will print out the step and its accompanying  table and then **stop completely**.

**Comment by evanjtravis** [comment]
Nevermind. It turns out that I had a `sys.exit()` call that was mal-indented (instead of exiting during a certain condition, I was exiting at the end of the `after_step()` hook)
