### ISSUE TITLE
rerun formatter doesn't works with Gherkin v6

### ISSUE THREAD

**Issue by dunossauro** [behave/behave#759]
I create a [simple project](https://github.com/dunossauro/behave-gherkin-v6) to test gherking v6 features. And when I test rerun, formatter show this traceback.

Trace:
```Python
Traceback (most recent call last):
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/bin/behave", line 10, in <module>
    sys.exit(main())
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/__main__.py", lin
e 215, in main
    return run_behave(config)
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/__main__.py", lin
e 102, in run_behave

    failed = runner.run()
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/runner.py", line
808, in run
    return self.run_with_paths()
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/runner.py", line
828, in run_with_paths
    return self.run_model()
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/runner.py", line
630, in run_model
    failed = feature.run(self)
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/model.py", line 3
93, in run
    formatter_callback()
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/formatter/rerun.p
y", line 65, in eof
    for scenario in self.current_feature.walk_scenarios():
  File "/home/eduardo.mendes/.local/share/virtualenvs/behave-gherkin-v6-Rx_fylZL/lib/python3.7/site-packages/behave/model.py", line 2
31, in walk_scenarios
    assert isinstance(run_item, Scenario)
```

**Comment by jenisys** [comment]
@dunossauro 
Sorry, I cannot reproduce your findings.
The rerun formatter works for me even when failing scenarios occur within rules.

Are you using the current HEAD of the Git repository ?
If not, recheck your findings w/ it and/or use `examples/gherkin_v6/features/rule_fails.feature` (or similar).

HINT: At least the line numbers in your traceback differ from mine. Your are probably not using HEAD.

**Comment by jenisys** [comment]
Reopen

>
