### ISSUE TITLE
Pretty Formatter: UnicodeEncodeError in Feature File

### ISSUE THREAD

**Issue by Songyu-Wang** [behave/behave#766]
Hello,
I have a feature file that contains emoji that is used as input in a example table
```
 | J   | customer            | short2     | 2000-01-30 | _                    | Pl😄 N'             | 
```
When I run it locally on my Mac with python3.6, it works fine and my json.pretty result is generated
```
    "rows": [
              [
                "short2",
                "RETURNED",
                "site",
                "short2",
                "2000-01-30",
                "_",
                "Pl\ud83d\ude04 N'"
              ]
            ]
```

However when I run the same code on Jenkins (Linux with python3.6). I get this error:
```
   | short2 | RETURNED | site | short2     | 2000-01-30 | _                    | Exception UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f604' in position 2: ordinal not in range(128)
	 Traceback (most recent call last):
	   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
	     "__main__", mod_spec)
	   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
	     exec(code, run_globals)
	   File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 187, in <module>
	     sys.exit(main())
	   File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 183, in main
	     return run_behave(config)
	   File "/usr/local/lib/python3.6/site-packages/behave/__main__.py", line 127, in run_behave
	     failed = runner.run()
	   File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 804, in run
	     return self.run_with_paths()
	   File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 824, in run_with_paths
	     return self.run_model()
	   File "/usr/local/lib/python3.6/site-packages/behave/runner.py", line 626, in run_model
	     failed = feature.run(self)
	   File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 321, in run
	     failed = scenario.run(runner)
	   File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 1114, in run
	     failed = scenario.run(runner)
	   File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 711, in run
	     if not step.run(runner):
	   File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 1311, in run
	     formatter.match(match)
	   File "/usr/local/lib/python3.6/site-packages/behave/formatter/pretty.py", line 132, in match
	     self._match.location, self.monochrome)
	   File "/usr/local/lib/python3.6/site-packages/behave/formatter/pretty.py", line 330, in print_step
	     self.table(step.table)
	   File "/usr/local/lib/python3.6/site-packages/behave/formatter/pretty.py", line 195, in table
	     self.stream.write(self.color(cell, None, j))
	 UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f604' in position 2: ordinal not in range(128)
```

You can notice the "decoded" character is not the same from both run. I just can't figure out what may be wrong. By going through the behave code. All feature files should be read as utf-8 no matter what. And py3 default is utf-8. 
Can anyone think of where the encoding may be messed up? 
Thank you

**Comment by Songyu-Wang** [comment]
My guess is the json formatter can handle non ascii chars correctly but plain text formatter cannot?

**Comment by jenisys** [comment]
The problem is in the pretty formatter.

Maybe your terminal is not setup for UTF-8 on Linux.
```sh
# -- CHECK ENVIRONMENT VARIABLES: In the shell
# HINT: Result on my MacBook.
$ env | grep UTF
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
```

If `LANG` environment variable is undefined, this means `LANG=C` (which means you are in ASCII mode).

**Comment by jenisys** [comment]
NOT REPRODUCIBLE (for me):
Feature check runs without any problem on Travis CI with Linux and Python3.7, Python2.7 with current HEAD of the Git repository.

**Comment by Songyu-Wang** [comment]
That may be why, but I don't have access to check our Jenkins machine, so I can't know for sure. Let's close this for now and we can reopen it if anyone else has the same issue
