### ISSUE TITLE
Behave runner.py bug, "recovered safely" but seems a bit strange

### ISSUE THREAD

**Issue by RichardBruskiewich** [behave/behave#799]
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_xml.py", line 282, in frame_vars_to_xml
    xml += var_to_xml(v, str(k), evaluate_full_value=eval_full_val)
  File "C:\Program Files\JetBrains\PyCharm 2019.2\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_xml.py", line 369, in var_to_xml
    elif hasattr(v, "__len__") and not is_string(v):
  File "C:\Users\Richard\PycharmProjects\translator-testing-framework\venv\lib\site-packages\behave\runner.py", line 315, in __getattr__
    return self.__dict__[attr]
KeyError: '__len__'
Unexpected error, recovered safely.
```

**Comment by jenisys** [comment]
* Which version of `behave` are you using ?

JetBrains seems to be using some dirty tricks that you should normally not use (`__len__()`).

**Comment by GareeTest** [comment]
I have this issue too, it doesn't seem to impact anything, but is annoying when I am debugging. Running behave 1.2.6

**Comment by bv** [comment]
> I have this issue too, it doesn't seem to impact anything, but is annoying when I am debugging. Running behave 1.2.6

during debugging evaluating expressions faces same error.

**Comment by essamzaroura** [comment]
how i can solve it? please provide me solution?

**Comment by karpaivan** [comment]
Observing same issue on Behave 1.2.6 using PyCharm 2019.3.3
On PyCharm 2019.2.5 everything is fine

**Comment by bv** [comment]
... updated this morning. Version is 2019.3.3 build #PY-193.6494.30 as 6 Fab 2020
the issue is not reproduced any more.

**Comment by ilya1200** [comment]
Also using  Behave 1.2.6 and PyCharm 2019.3.3, have this annoying problem ..
What is the solution?

**Comment by brianbartilet** [comment]
+1 PyCharm version 2019.3.3, behave 1.2.6

**Comment by ronxchen** [comment]
same issue here: PyCharm version 2019.3.3, behave 1.2.6

**Comment by jenisys** [comment]
Reopen
