### ISSUE TITLE
behave project not running in docker mode. 

### ISSUE THREAD

**Issue by chunji08** [behave/behave#961]
I am trying to package my behave project in a docker image, but somehow the created image is not working. 

1) Here is highlights my project structure: 

```
> features/
> ├── blueprint
> │   └── blueprint.details_212F.feature
> ├── environment.cfg
> ├── environment.py
> ├── lib
> │       └── pages
> │       ├── base.py
> │       ├── blueprint
> │       │        ├──....
> └── steps
>         ├──  .... 
```

2) and on my local, I usually run the behave case in such command: 
``` 
behave features/blueprint/blueprint.details_212F.feature
```
3) once I have the the image created, I am trying to run the image in such command: 
```
 docker run <image id>  behave  <my project>/features/blueprint/blueprint.details_212F.feature
```
4) And I have received this type of failure: 
```
Exception ModuleNotFoundError: No module named 'features'
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/usr/local/lib/python3.8/dist-packages/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/usr/local/lib/python3.8/dist-packages/behave/runner.py", line 804, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.8/dist-packages/behave/runner.py", line 808, in run_with_paths
    self.load_hooks()
  File "/usr/local/lib/python3.8/dist-packages/behave/runner.py", line 784, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "/usr/local/lib/python3.8/dist-packages/behave/runner_util.py", line 386, in exec_file
    exec(code, globals_, locals_)
  File "<my project>/features/environment.py", line 9, in <module>
    from features.lib.pages.base import Base
ModuleNotFoundError: No module named 'features'

```

This is the beginning of my code in the  environment.py file.  

```
import base64
import configparser
import http.client
import logging
import os
import time

import requests
from features.lib.pages.base import Base
... 

```
Any ideas how to make it working ? 

Thanks a lot. 

Chun Ji

**Comment by bittner** [comment]
This problem is unrelated to Behave, it's purely about using Docker properly.

You don't seem to mount the feature files (and their step implementation) into your Docker container.

Use the `-v` option of the `docker run` command to do this. ([Reference](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems))
