### ISSUE TITLE
Parser failure when calling step from execute steps

### ISSUE THREAD

**Issue by mglowinski93** [behave/behave#964]
Sometimes (not always!) parser fails to parse parameter, when calling step from `execute_steps`.

Calling step:
```
@given("cooling temperature setpoint is set to {cooling_temperature_setpoint:Float}°C")
def step_impl(context, cooling_temperature_setpoint):
    context.controller.channel_1.set_cooling_temperature_setpoint(cooling_temperature_setpoint)
    context.execute_steps(u"heating plug cooling temperature setpoint is equal to {}°C".format(cooling_temperature_setpoint)
```

Then step:
```
@then(
    "heating plug heating temperature setpoint is equal to {temperature_setpoint:Float}°C"
)
def step_impl(context, temperature_setpoint):
    assert context.controller.channel_1.heating_temperature_setpoint == temperature_setpoint
```

Stacktrace:
```
    Given heating temperature setpoint is set to 20°C                                # tests/esmart_plugs_tests/th_plug/features/steps/given.py:130 9.593s
      Traceback (most recent call last):
        File "/home/pi/.local/share/virtualenvs/PlugsTester-EektgUbj/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/pi/.local/share/virtualenvs/PlugsTester-EektgUbj/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "tests/esmart_plugs_tests/th_plug/features/steps/given.py", line 144, in step_impl
          heating_temperature_setpoint
        File "/home/pi/.local/share/virtualenvs/PlugsTester-EektgUbj/lib/python3.7/site-packages/behave/runner.py", line 390, in execute_steps
          steps = self.feature.parser.parse_steps(steps_text)
        File "/home/pi/.local/share/virtualenvs/PlugsTester-EektgUbj/lib/python3.7/site-packages/behave/parser.py", line 609, in parse_steps
          self.action(line)
        File "/home/pi/.local/share/virtualenvs/PlugsTester-EektgUbj/lib/python3.7/site-packages/behave/parser.py", line 290, in action
          raise ParserError(msg, None, self.filename)
      behave.parser.ParserError: Failed to parse <string>: 
      Parser failure in state steps, at line 1: "heating plug heating temperature setpoint is equal to 20.0°C"
```

Any tip what can be a reason?

**Comment by mglowinski93** [comment]
My bad,
it seems to be an issue of missing `step` while calling step.

Example:
```
          u"""
            Then thermostat plug heating temperature setpoint is equal to {}°C
            """.format(
                heating_temperature_setpoint
            )
```
