### ISSUE TITLE
behave gives "TypeError: not all arguments converted during string formatting" on all errors and stops execution

### ISSUE THREAD

**Issue by digvijaysinghCiitizen** [behave/behave#966]
Whenever any error is encountered during behave execution, no matter the error, it always gives this error - "TypeError: not all arguments converted during string formatting". and the execution stops. If i have multiple examples, it should move to the next one. 
I have this error coming up a simple assert as well, when assert is false, it gives this error and stops execution. Below is the complete error. Can you help

```
Exception TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/usr/local/lib/python3.9/site-packages/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/usr/local/lib/python3.9/site-packages/behave/runner.py", line 804, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.9/site-packages/behave/runner.py", line 824, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python3.9/site-packages/behave/runner.py", line 626, in run_model
    failed = feature.run(self)
  File "/usr/local/lib/python3.9/site-packages/behave/model.py", line 321, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python3.9/site-packages/behave/model.py", line 1114, in run
    failed = scenario.run(runner)
  File "/usr/local/lib/python3.9/site-packages/behave/model.py", line 711, in run
    if not step.run(runner):
  File "/usr/local/lib/python3.9/site-packages/behave/model.py", line 1368, in run
    self.captured = runner.capture_controller.captured
  File "/usr/local/lib/python3.9/site-packages/behave/capture.py", line 133, in captured
    log_out = _text(self.log_capture.getvalue())
  File "/usr/local/lib/python3.9/site-packages/behave/log_capture.py", line 99, in getvalue
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
  File "/usr/local/lib/python3.9/site-packages/behave/log_capture.py", line 99, in <genexpr>
    return '\n'.join(self.formatter.format(r) for r in self.buffer)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by jenisys** [comment]
@digvijaysinghCiitizen 
Check your logging statements.
It is probable that you are missing a parameter or provided one (or more) placeholder to many, like:

```python
import logging

name1 = "Alice"
name2 = "Bob"
logging.warn("Example 1: %s and %s", name1)   # second parameter expected but missing
logging.warn("Example 2: %s", name1, name2)   # second parameter provided but not expected
```

**Comment by jenisys** [comment]
NO ACTIVITY => Close it.
